
[font]
size = 14.0

[font.bold]
family = "Roboto Mono for Powerline"
style = "Bold"

[font.normal]
family = "Roboto Mono for Powerline"
style = "Regular"

[font.offset]
x = 1
y = 1

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.9

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 8
y = 0

[general]
import = ["~/ghq/github.com/dracula/alacritty/dracula.toml"]
