[[plugins]]
repo = 'dracula/vim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'cocopon/vaffle.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tmhedberg/matchit'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'w0rp/ale'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'ToruIwashita/git-switcher.vim'

[[plugins]]
repo = 'othree/html5.vim'
on_i = 1
on_ft = ['html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_i = 1
on_ft = ['css','sass','scss']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_i = 1
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/yajs.vim'
on_i = 1
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_i = 1
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_i = 1
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
depends = ['yajs.vim']
on_i = 1
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'mxw/vim-jsx'
on_i = 1
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'ternjs/tern_for_vim'
on_i = 1
on_ft = ['javascript', 'javascript.jsx']
hook_source = '''
  let g:dein#plugin.build = "npm install"
'''

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript', 'javascript.jsx']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'clausreinke/typescript-tools.vim'
on_ft = ['typescript']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby', 'eruby', 'haml']

[[plugins]]
repo = 'skwp/vim-rspec'
on_ft = ['ruby', 'eruby', 'haml']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'eruby', 'haml']

[[plugins]]
repo = '5t111111/denite-rails'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'prettier/vim-prettier'
on_ft = ['javascript']

[[plugins]]
repo = 'epilande/vim-es2015-snippets'
on_i = 1
on_ft = ['javascript']

[[plugins]]
repo = 'epilande/vim-react-snippets'
on_i = 1
on_ft = ['javascript']



[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'stephenway/postcss.vim'
on_ft = ['css']

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'airblade/vim-gitgutter'

