[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'Shougo/vimfiler'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'Jagua/vim-denite-ghq'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tmhedberg/matchit'

[[plugins]]
repo = 'surround.vim'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'ToruIwashita/git-switcher.vim'

[[plugins]]
repo = 'othree/html5.vim'
on_i = 1
on_ft = ['html']

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_i = 1
on_ft = ['css','sass','scss']

[[plugins]]
repo = 'digitaltoad/vim-pug'
on_i = 1
on_ft = ['pug']

[[plugins]]
repo = 'slim-template/vim-slim'
on_i = 1
on_ft = ['slim']

[[plugins]]
repo = 'othree/yajs.vim'
on_i = 1

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
depends = ['yajs.vim']
on_i = 1
on_ft = ['javascript']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_i = 1

[[plugins]]
repo = 'othree/es.next.syntax.vim'
on_i = 1

[[plugins]]
repo = 'nicklasos/vim-jsx-riot'
on_i = 1
on_ft = ['tag']

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'clausreinke/typescript-tools.vim'
on_ft = ['typescript']

[[plugins]]
repo = 'claco/jasmine.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby', 'eruby', 'haml']

[[plugins]]
repo = 'skwp/vim-rspec'
on_ft = ['ruby', 'eruby', 'haml']

[[plugins]]
repo = 'ruby.vim'
on_ft = ['ruby', 'eruby', 'haml']

[[plugins]]
repo = 'rails.vim'
on_ft = ['ruby', 'eruby', 'haml']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'eruby', 'haml']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'toyamarinyon/vim-swift'
on_ft = ['swift']

[[plugins]]
repo = 'Keithbsmiley/swift.vim'
on_ft = ['swift']

[[plugins]]
repo = 'epilande/vim-es2015-snippets'
on_i = 1
on_ft = ['javascript']

[[plugins]]
repo = 'epilande/vim-react-snippets'
on_i = 1
on_ft = ['javascript']

[[plugins]]
repo = 'SirVer/ultisnips'
on_i = 1

